/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIOS;

//import com.sun.awt.AWTUtilities;
import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import sun.misc.BASE64Decoder;
import sun.misc.BASE64Encoder;

/**
 *
 * @author FRANK
 */
public class MEN extends javax.swing.JFrame {
int xx;

    /**
     * Creates new form MENUNUEVO
     */
    int yy;
    MENSAJE2 men=new MENSAJE2();
    NCLIENTE ncliente=new NCLIENTE();
//    HISTORIAS HISTO=new HISTORIAS();
    File fichero = null;
    private JPanel contentPane;
    public MEN() {
        this.setUndecorated(true);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/IMAGENES/nueeeee.png")).getImage());
        Shape forma=new RoundRectangle2D.Double(0,0, this.getBounds().width, this.getBounds().height,30,30);
        AWTUtilities.setWindowShape(this,forma);
        
        this.setLocationRelativeTo(null);
     
        btnclientes.setVisible(false);
        btnproveedores.setVisible(false);
        btnproductos.setVisible(false);
//        btntablas.setVisible(false);
//        btnmovimientos.setVisible(false);
        btnentrada.setVisible(false);
        btnsalida.setVisible(false);
        btnentrada2.setVisible(false);
        btnsalida2.setVisible(false);
        btndocentrada.setVisible(false);
        btndocsalida.setVisible(false);
        producentrada.setVisible(false);
        producsalida.setVisible(false);
        JDBC.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel18.setVisible(false);
        jLabel17.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
        btnmenu2.setVisible(false);
        
        MENU.setVisible(false);
        
//        jButton5.setVisible(false);
//        jLabel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        jLabel1 = new javax.swing.JLabel();
        bOTON1 = new BOTON.BOTON();
        bOTON_MINIMIZAR1 = new BOTON.BOTON_MINIMIZAR();
        MENU1 = new javax.swing.JLabel();
        PALO = new javax.swing.JLabel();
        PALO1 = new javax.swing.JLabel();
        TRIANGULO = new javax.swing.JLabel();
        btnmenu = new javax.swing.JButton();
        btnmenu2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        MENU = new javax.swing.JPanel();
        producentrada = new BOTON.ENTRADA();
        producsalida = new BOTON.SALIDA();
        JDBC = new BOTON.BOTON_CUADROROJO();
        btntablas = new BOTON.TABLAS();
        btnmovimientos = new BOTON.MOVIMIENTOS();
        btnconsultas = new BOTON.CONSULTAS();
        btnclientes = new BOTON.CLIENTES();
        btnproductos = new BOTON.PRODUCTOS();
        btnproveedores = new BOTON.PROVEEDORES();
        btnentrada = new BOTON.ENTRADA();
        btnsalida = new BOTON.SALIDA();
        btnentrada2 = new BOTON.ENTRADA();
        btndocentrada = new BOTON.DOCENTRADA();
        btndocsalida = new BOTON.DOCSALIDA();
        btnsalida2 = new BOTON.SALIDA();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        PALO2 = new javax.swing.JLabel();
        PALO3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jPopupMenu1.setBackground(new java.awt.Color(28, 30, 34));
        jPopupMenu1.setForeground(new java.awt.Color(28, 30, 34));
        jPopupMenu1.setAlignmentY(0.0F);
        jPopupMenu1.setBorder(null);
        jPopupMenu1.setBorderPainted(false);
        jPopupMenu1.setOpaque(false);

        jMenuItem1.setBackground(new java.awt.Color(28, 30, 34));
        jMenuItem1.setForeground(new java.awt.Color(28, 30, 34));
        jMenuItem1.setText("Eliminar");
        jMenuItem1.setAlignmentX(0.0F);
        jMenuItem1.setAlignmentY(0.0F);
        jMenuItem1.setBorder(null);
        jMenuItem1.setContentAreaFilled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        panelNice1.setBackground(new java.awt.Color(28, 30, 34));
        panelNice1.setBorderColor(new java.awt.Color(30, 30, 30));
        panelNice1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");
        panelNice1.add(jLabel1);
        jLabel1.setBounds(50, 35, 90, 28);

        bOTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOTON1ActionPerformed(evt);
            }
        });
        panelNice1.add(bOTON1);
        bOTON1.setBounds(990, 10, 50, 50);

        bOTON_MINIMIZAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOTON_MINIMIZAR1ActionPerformed(evt);
            }
        });
        panelNice1.add(bOTON_MINIMIZAR1);
        bOTON_MINIMIZAR1.setBounds(932, 10, 50, 50);

        MENU1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ARRIBAAZUL.png"))); // NOI18N
        panelNice1.add(MENU1);
        MENU1.setBounds(0, -4, 1160, 210);

        PALO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/paloPublic.png"))); // NOI18N
        panelNice1.add(PALO);
        PALO.setBounds(990, 94, 80, 10);

        PALO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/paloPublic.png"))); // NOI18N
        panelNice1.add(PALO1);
        PALO1.setBounds(1, 94, 1000, 10);

        TRIANGULO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/paloPublicTRUANGULO.png"))); // NOI18N
        panelNice1.add(TRIANGULO);
        TRIANGULO.setBounds(-130, -40, 1200, 140);

        btnmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/MENUARRIBANUEVO.png"))); // NOI18N
        btnmenu.setBorder(null);
        btnmenu.setBorderPainted(false);
        btnmenu.setContentAreaFilled(false);
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        panelNice1.add(btnmenu);
        btnmenu.setBounds(413, 69, 250, 28);

        btnmenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/MENUABAJONUEVO.png"))); // NOI18N
        btnmenu2.setBorder(null);
        btnmenu2.setBorderPainted(false);
        btnmenu2.setContentAreaFilled(false);
        btnmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenu2ActionPerformed(evt);
            }
        });
        panelNice1.add(btnmenu2);
        btnmenu2.setBounds(413, 61, 250, 35);

        jPanel6.setBackground(new java.awt.Color(28, 30, 34));
        jPanel6.setLayout(null);
        panelNice1.add(jPanel6);
        jPanel6.setBounds(154, 100, 800, 310);

        MENU.setBackground(new java.awt.Color(0, 0, 0));
        MENU.setOpaque(false);
        MENU.setLayout(null);

        producentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producentradaActionPerformed(evt);
            }
        });
        MENU.add(producentrada);
        producentrada.setBounds(100, 25, 85, 36);

        producsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producsalidaActionPerformed(evt);
            }
        });
        MENU.add(producsalida);
        producsalida.setBounds(200, 25, 85, 36);

        JDBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDBCActionPerformed(evt);
            }
        });
        MENU.add(JDBC);
        JDBC.setBounds(275, 43, 70, 63);

        btntablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntablasActionPerformed(evt);
            }
        });
        MENU.add(btntablas);
        btntablas.setBounds(153, 62, 85, 36);

        btnmovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmovimientosActionPerformed(evt);
            }
        });
        MENU.add(btnmovimientos);
        btnmovimientos.setBounds(338, 60, 85, 36);

        btnconsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultasActionPerformed(evt);
            }
        });
        MENU.add(btnconsultas);
        btnconsultas.setBounds(535, 61, 85, 36);

        btnclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientesActionPerformed(evt);
            }
        });
        MENU.add(btnclientes);
        btnclientes.setBounds(65, 25, 85, 36);

        btnproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductosActionPerformed(evt);
            }
        });
        MENU.add(btnproductos);
        btnproductos.setBounds(152, 25, 85, 36);

        btnproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproveedoresActionPerformed(evt);
            }
        });
        MENU.add(btnproveedores);
        btnproveedores.setBounds(240, 25, 85, 36);

        btnentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentradaActionPerformed(evt);
            }
        });
        MENU.add(btnentrada);
        btnentrada.setBounds(295, 25, 85, 36);

        btnsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalidaActionPerformed(evt);
            }
        });
        MENU.add(btnsalida);
        btnsalida.setBounds(380, 25, 85, 36);

        btnentrada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrada2ActionPerformed(evt);
            }
        });
        MENU.add(btnentrada2);
        btnentrada2.setBounds(487, 25, 85, 36);

        btndocentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocentradaActionPerformed(evt);
            }
        });
        MENU.add(btndocentrada);
        btndocentrada.setBounds(580, 25, 85, 36);

        btndocsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocsalidaActionPerformed(evt);
            }
        });
        MENU.add(btndocsalida);
        btndocsalida.setBounds(623, 61, 85, 36);

        btnsalida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalida2ActionPerformed(evt);
            }
        });
        MENU.add(btnsalida2);
        btnsalida2.setBounds(447, 61, 85, 36);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LILA.gif"))); // NOI18N
        MENU.add(jLabel22);
        jLabel22.setBounds(70, 35, 90, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LILA.gif"))); // NOI18N
        MENU.add(jLabel23);
        jLabel23.setBounds(148, 35, 90, 40);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LILA.gif"))); // NOI18N
        MENU.add(jLabel24);
        jLabel24.setBounds(230, 35, 90, 40);

        jLabel2.setFont(new java.awt.Font("DS-Digital", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CASILLAS2.png"))); // NOI18N
        MENU.add(jLabel2);
        jLabel2.setBounds(0, 0, 770, 97);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LILA.gif"))); // NOI18N
        MENU.add(jLabel13);
        jLabel13.setBounds(62, 35, 90, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LILA.gif"))); // NOI18N
        MENU.add(jLabel14);
        jLabel14.setBounds(150, 35, 90, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LILA.gif"))); // NOI18N
        MENU.add(jLabel15);
        jLabel15.setBounds(237, 35, 100, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LILA.gif"))); // NOI18N
        MENU.add(jLabel16);
        jLabel16.setBounds(330, 35, 100, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LILA.gif"))); // NOI18N
        MENU.add(jLabel17);
        jLabel17.setBounds(612, 40, 100, 40);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LILA.gif"))); // NOI18N
        MENU.add(jLabel18);
        jLabel18.setBounds(524, 35, 100, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LILA.gif"))); // NOI18N
        MENU.add(jLabel19);
        jLabel19.setBounds(260, 35, 100, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LILA.gif"))); // NOI18N
        MENU.add(jLabel20);
        jLabel20.setBounds(410, 35, 100, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LILA.gif"))); // NOI18N
        MENU.add(jLabel21);
        jLabel21.setBounds(442, 40, 100, 40);

        panelNice1.add(MENU);
        MENU.setBounds(164, 100, 780, 94);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(null);
        panelNice1.add(jPanel5);
        jPanel5.setBounds(164, 0, 780, 97);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ABAJONEGRIFIJO.png"))); // NOI18N
        panelNice1.add(jLabel11);
        jLabel11.setBounds(0, 432, 1070, 170);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/perfil-botton_off.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/perfil-botton_on.png"))); // NOI18N
        jButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/perfil-botton.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelNice1.add(jButton4);
        jButton4.setBounds(460, 140, 70, 60);

        PALO2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/paloPublic.png"))); // NOI18N
        panelNice1.add(PALO2);
        PALO2.setBounds(1, 600, 1000, 10);

        PALO3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/paloPublic.png"))); // NOI18N
        panelNice1.add(PALO3);
        PALO3.setBounds(990, 603, 80, 4);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ABAJO.png"))); // NOI18N
        panelNice1.add(jLabel7);
        jLabel7.setBounds(0, 570, 1070, 290);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/DERECHA.png"))); // NOI18N
        panelNice1.add(jLabel8);
        jLabel8.setBounds(990, 0, 400, 690);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/IZQUIERDA.png"))); // NOI18N
        panelNice1.add(jLabel9);
        jLabel9.setBounds(-130, 0, 350, 690);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        panelNice1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1070, 100);

        jPanel1.add(panelNice1);
        panelNice1.setBounds(2, 2, 1066, 685);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ncliente.setVisible(true);
//        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed
   
    
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
      xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
 Point point = MouseInfo.getPointerInfo().getLocation() ;
        setLocation(point.x - xx, point.y - yy)  ;        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseDragged

    private void bOTON_MINIMIZAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOTON_MINIMIZAR1ActionPerformed
     this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_bOTON_MINIMIZAR1ActionPerformed

    private void bOTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOTON1ActionPerformed
             try{
            int dialogButton=JOptionPane.YES_NO_OPTION;
            int result=JOptionPane.showConfirmDialog(this, "Desea Cerrar El Sistema??","CERRAR SISTEMA",dialogButton);

            if (result==0) {
                System.exit(0);
            }
        }catch(Exception o){
            JOptionPane.showMessageDialog(null,"error");
        }
    }//GEN-LAST:event_bOTON1ActionPerformed

    private void btntablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntablasActionPerformed
     
        btnclientes.setVisible(true);
        btnproveedores.setVisible(true);
        btnproductos.setVisible(true);
        jLabel13.setVisible(true);
        jLabel14.setVisible(true);
        jLabel15.setVisible(true);
        
        jLabel20.setVisible(false);
        jLabel16.setVisible(false);
        jLabel19.setVisible(false);
        jLabel21.setVisible(false);
        jLabel18.setVisible(false);
        jLabel17.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
        
        JDBC.setVisible(false);
        btnentrada.setVisible(false);
        btnsalida.setVisible(false);
        btnentrada2.setVisible(false);
        btnsalida2.setVisible(false);
        btndocentrada.setVisible(false);
        btndocsalida.setVisible(false);
        producentrada.setVisible(false);
        producsalida.setVisible(false);
    }//GEN-LAST:event_btntablasActionPerformed

    private void btnclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientesActionPerformed
        btnclientes.setVisible(false);
        btnproveedores.setVisible(false);
        btnproductos.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel20.setVisible(false);
        jLabel16.setVisible(false);
        jLabel19.setVisible(false);
        btnentrada.setVisible(false);
        btnsalida.setVisible(false);
        btnentrada2.setVisible(false);
        btnsalida2.setVisible(false);
        btndocentrada.setVisible(false);
        btndocsalida.setVisible(false);
    }//GEN-LAST:event_btnclientesActionPerformed

    private void btnproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductosActionPerformed
        btnclientes.setVisible(false);
        btnproveedores.setVisible(false);
        btnproductos.setVisible(false);
//        jLabel13.setVisible(false);
//        jLabel14.setVisible(false);
//        jLabel15.setVisible(false);
        jLabel20.setVisible(false);
        jLabel16.setVisible(false);
        jLabel19.setVisible(false);
        btnentrada.setVisible(false);
        btnsalida.setVisible(false);
        btnentrada2.setVisible(false);
        btnsalida2.setVisible(false);
        btndocentrada.setVisible(false);
        btndocsalida.setVisible(false);
        
//        jLabel22.setVisible(true);
//        jLabel23.setVisible(true);
//        jLabel24.setVisible(true);
        producentrada.setVisible(true);
        producsalida.setVisible(true);
    }//GEN-LAST:event_btnproductosActionPerformed

    private void btnproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproveedoresActionPerformed
            btnclientes.setVisible(false);
        btnproveedores.setVisible(false);
        btnproductos.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel20.setVisible(false);
        jLabel16.setVisible(false);
        jLabel19.setVisible(false);
        btnentrada.setVisible(false);
        btnsalida.setVisible(false);
        btnentrada2.setVisible(false);
        btnsalida2.setVisible(false);
        btndocentrada.setVisible(false);
        btndocsalida.setVisible(false);
    }//GEN-LAST:event_btnproveedoresActionPerformed

    private void btnmovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmovimientosActionPerformed
       
        
        JDBC.setVisible(true);
        btnentrada.setVisible(true);
        btnsalida.setVisible(true);
        jLabel16.setVisible(true);
        jLabel19.setVisible(true);
        jLabel20.setVisible(true);
        
        btnclientes.setVisible(false);
        btnproveedores.setVisible(false);
        btnproductos.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel21.setVisible(false);
        jLabel18.setVisible(false);
        jLabel17.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
        
        btnentrada2.setVisible(false);
        btnsalida2.setVisible(false);
        btndocentrada.setVisible(false);
        btndocsalida.setVisible(false);
        producentrada.setVisible(false);
        producsalida.setVisible(false);
    }//GEN-LAST:event_btnmovimientosActionPerformed

    private void btnentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentradaActionPerformed
        
        btnentrada.setVisible(false);
        btnsalida.setVisible(false);
        jLabel16.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        btnproductos.setVisible(false);
        btnproveedores.setVisible(false);
        btnclientes.setVisible(false);
        btnentrada2.setVisible(false);
        btnsalida2.setVisible(false);
        btndocentrada.setVisible(false);
        btndocsalida.setVisible(false);
    }//GEN-LAST:event_btnentradaActionPerformed

    private void btnsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalidaActionPerformed
        
        btnentrada.setVisible(false);
        btnsalida.setVisible(false);
        jLabel16.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        btnproductos.setVisible(false);
        btnproveedores.setVisible(false);
        btnclientes.setVisible(false);
        btnentrada2.setVisible(false);
        btnsalida2.setVisible(false);
        btndocentrada.setVisible(false);
        btndocsalida.setVisible(false);
    }//GEN-LAST:event_btnsalidaActionPerformed

    private void btnconsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultasActionPerformed
       
        btnentrada2.setVisible(true);
        btnsalida2.setVisible(true);
        btndocentrada.setVisible(true);
        btndocsalida.setVisible(true);
        jLabel21.setVisible(true);
        jLabel18.setVisible(true);
        jLabel17.setVisible(true);
        
        btnclientes.setVisible(false);
        btnproveedores.setVisible(false);
        btnproductos.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel20.setVisible(false);
        jLabel16.setVisible(false);
        jLabel19.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
        JDBC.setVisible(false);
        btnentrada.setVisible(false);
        btnsalida.setVisible(false);
        producentrada.setVisible(false);
        producsalida.setVisible(false);
        
    }//GEN-LAST:event_btnconsultasActionPerformed

    private void btnsalida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalida2ActionPerformed
        jLabel21.setVisible(false);
        jLabel18.setVisible(false);
        jLabel17.setVisible(false);
        btnentrada2.setVisible(false);
        btnsalida2.setVisible(false);
        btndocentrada.setVisible(false);
        btndocsalida.setVisible(false);
        
        
        btnproductos.setVisible(false);
        btnproveedores.setVisible(false);
        btnclientes.setVisible(false);
        btnentrada.setVisible(false);
        btnsalida.setVisible(false);
    }//GEN-LAST:event_btnsalida2ActionPerformed

    private void btnentrada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrada2ActionPerformed
        jLabel21.setVisible(false);
        jLabel18.setVisible(false);
        jLabel17.setVisible(false);
        btnentrada2.setVisible(false);
        btnsalida2.setVisible(false);
        btndocentrada.setVisible(false);
        btndocsalida.setVisible(false);
        
        btnproductos.setVisible(false);
        btnproveedores.setVisible(false);
        btnclientes.setVisible(false);
        btnentrada.setVisible(false);
        btnsalida.setVisible(false);
    }//GEN-LAST:event_btnentrada2ActionPerformed

    private void btndocentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocentradaActionPerformed
        jLabel21.setVisible(false);
        jLabel18.setVisible(false);
        jLabel17.setVisible(false);
        btnentrada2.setVisible(false);
        btnsalida2.setVisible(false);
        btndocentrada.setVisible(false);
        btndocsalida.setVisible(false);
        
                btnproductos.setVisible(false);
        btnproveedores.setVisible(false);
        btnclientes.setVisible(false);
        btnentrada.setVisible(false);
        btnsalida.setVisible(false);
    }//GEN-LAST:event_btndocentradaActionPerformed

    private void btndocsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocsalidaActionPerformed
        jLabel21.setVisible(false);
        jLabel18.setVisible(false);
        jLabel17.setVisible(false);
        btnentrada2.setVisible(false);
        btnsalida2.setVisible(false);
        btndocentrada.setVisible(false);
        btndocsalida.setVisible(false);
        
                btnproductos.setVisible(false);
        btnproveedores.setVisible(false);
        btnclientes.setVisible(false);
        btnentrada.setVisible(false);
        btnsalida.setVisible(false);
    }//GEN-LAST:event_btndocsalidaActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
       int posicion2 = MENU.getX();
        int posicion = btnmenu.getX();

        if (posicion > 10) {
            Animacion.Animacion.subir(69, -36, 25, 7, btnmenu);
            Animacion.Animacion.subir(164, -3, 25, 7, MENU);
            Animacion.Animacion.bajar(61, 100, 25, 7, btnmenu2);
            btnmenu2.setVisible(true);
//            if (posicion2<165) {
                MENU.setVisible(true);
//            }
            
//fotoregistro.setIcon(new ImageIcon(getClass().getResource("/IMAGENES/user_icom2.png")));
    }else{

//            Animacion.Animacion.bajar(-30, 61, 25, 7, btnmenu);
//            Animacion.Animacion.bajar(0, 164, 25, 7, MENU);
//            //
            //textField7.setText(fotomenu.getText());

        }
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btnmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenu2ActionPerformed
         
        int posicion2 = MENU.getX();
        int posicion = btnmenu2.getX();

        if (posicion > 10) {
            Animacion.Animacion.bajar(100, 61, 25, 7, btnmenu2);
            Animacion.Animacion.bajar(-36, 69, 25, 7, btnmenu);
            Animacion.Animacion.bajar(-3, 164, 25, 7, MENU);
            
            btnmenu2.setVisible(false);
            
          
//            if (posicion2<165) {
//                MENU.setVisible(true);
//            }
            
//fotoregistro.setIcon(new ImageIcon(getClass().getResource("/IMAGENES/user_icom2.png")));
    }else{

//            Animacion.Animacion.bajar(-30, 61, 25, 7, btnmenu);
//            Animacion.Animacion.bajar(0, 164, 25, 7, MENU);
//            //
            //textField7.setText(fotomenu.getText());

        }
    }//GEN-LAST:event_btnmenu2ActionPerformed

  
    
    private void producentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producentradaActionPerformed
   
    }//GEN-LAST:event_producentradaActionPerformed

    private void producsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producsalidaActionPerformed
   
    }//GEN-LAST:event_producsalidaActionPerformed

    private void JDBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDBCActionPerformed
    
    }//GEN-LAST:event_JDBCActionPerformed

    
  
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    

        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static BOTON.BOTON_CUADROROJO JDBC;
    public static javax.swing.JPanel MENU;
    public static javax.swing.JLabel MENU1;
    public static javax.swing.JLabel PALO;
    public static javax.swing.JLabel PALO1;
    public static javax.swing.JLabel PALO2;
    public static javax.swing.JLabel PALO3;
    public static javax.swing.JLabel TRIANGULO;
    public static BOTON.BOTON bOTON1;
    public static BOTON.BOTON_MINIMIZAR bOTON_MINIMIZAR1;
    public static BOTON.CLIENTES btnclientes;
    public static BOTON.CONSULTAS btnconsultas;
    public static BOTON.DOCENTRADA btndocentrada;
    public static BOTON.DOCSALIDA btndocsalida;
    public static BOTON.ENTRADA btnentrada;
    public static BOTON.ENTRADA btnentrada2;
    public static javax.swing.JButton btnmenu;
    public static javax.swing.JButton btnmenu2;
    public static BOTON.MOVIMIENTOS btnmovimientos;
    public static BOTON.PRODUCTOS btnproductos;
    public static BOTON.PROVEEDORES btnproveedores;
    public static BOTON.SALIDA btnsalida;
    public static BOTON.SALIDA btnsalida2;
    public static BOTON.TABLAS btntablas;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel24;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JMenuItem jMenuItem2;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel5;
    public static javax.swing.JPanel jPanel6;
    public static javax.swing.JPopupMenu jPopupMenu1;
    public static javax.swing.JPopupMenu jPopupMenu2;
    public static org.edisoncor.gui.panel.PanelNice panelNice1;
    public static BOTON.ENTRADA producentrada;
    public static BOTON.SALIDA producsalida;
    // End of variables declaration//GEN-END:variables
}
